
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL
    env_file:
      - .env
    depends_on:
    - db
    volumes:
      - .:/app
    user: "1000:1000"
    restart: unless-stopped
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    env_file:
      - .env
    volumes:
      - postgres_data:/vat/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data: